python detection_ep.py # black-box detection
python detection_ep.py --prompt # white-box detection
python detection_ep.py --prompt --estimated_prompt --ai_source_est llama2 # enhanced black-box detection using estimated prompt generated by llama
python detection_ep.py --prompt --estimated_prompt --ai_source_est neural-chat # enhanced black-box detection using estimated prompt generated by neural-chat
python detection_ep.py --prompt --estimated_prompt --ai_source_est phi2 # enhanced black-box detection using estimated prompt generated by phi-2
python detection_ep.py --binoculars_only # black-box detection
python detection_ep.py --binoculars_only  --prompt # white-box detection
python detection_ep.py --binoculars_only  --prompt --estimated_prompt black-box --ai_source_est llama2 # enhanced black-box detection using estimated prompt generated by llama
python detection_ep.py --binoculars_only  --prompt --estimated_prompt black-box --ai_source_est neural-chat # enhanced black-box detection using estimated prompt generated by neural-chat
python detection_ep.py --binoculars_only  --prompt --estimated_prompt black-box --ai_source_est phi2 # enhanced black-box detection using estimated prompt generated by phi-2
python detection_ep.py --dataset_name writingprompts # black-box detection 
python detection_ep.py --dataset_name writingprompts --prompt # white-box detection
python detection_ep.py --dataset_name writingprompts --prompt --estimated_prompt black-box --ai_source_est llama2 # enhanced black-box detection using estimated prompt generated by llama
python detection_ep.py --dataset_name writingprompts --prompt --estimated_prompt black-box --ai_source_est neural-chat # enhanced black-box detection using estimated prompt generated by neural-chat
python detection_ep.py --dataset_name writingprompts --prompt --estimated_prompt black-box --ai_source_est phi2 # enhanced black-box detection using estimated prompt generated by phi-2
python detection_ep.py --dataset_name writingprompts --binoculars_only # black-box detection
python detection_ep.py --dataset_name writingprompts --binoculars_only  --prompt # white-box detection
python detection_ep.py --dataset_name writingprompts --binoculars_only  --prompt --estimated_prompt black-box --ai_source_est llama2 # enhanced black-box detection using estimated prompt generated by llama
python detection_ep.py --dataset_name writingprompts --binoculars_only  --prompt --estimated_prompt black-box --ai_source_est neural-chat # enhanced black-box detection using estimated prompt generated by neural-chat
python detection_ep.py --dataset_name writingprompts --binoculars_only  --prompt --estimated_prompt black-box --ai_source_est phi2 # enhanced black-box detection using estimated prompt generated by phi-2
python detection_ep.py --dataset_name HC3 # black-box detection
python detection_ep.py --dataset_name HC3 --prompt # white-box detection
python detection_ep.py --dataset_name HC3 --prompt --estimated_prompt black-box --ai_source_est llama2 # enhanced black-box detection using estimated prompt generated by llama
python detection_ep.py --dataset_name HC3 --prompt --estimated_prompt black-box --ai_source_est neural-chat # enhanced black-box detection using estimated prompt generated by neural-chat
python detection_ep.py --dataset_name HC3 --prompt --estimated_prompt black-box --ai_source_est phi2 # enhanced black-box detection using estimated prompt generated by phi-2
python detection_ep.py --dataset_name HC3 --binoculars_only # black-box detection
python detection_ep.py --dataset_name HC3 --binoculars_only  --prompt # white-box detection
python detection_ep.py --dataset_name HC3 --binoculars_only  --prompt --estimated_prompt black-box --ai_source_est llama2 # enhanced black-box detection using estimated prompt generated by llama
python detection_ep.py --dataset_name HC3 --binoculars_only  --prompt --estimated_prompt black-box --ai_source_est neural-chat # enhanced black-box detection using estimated prompt generated by neural-chat
python detection_ep.py --dataset_name HC3 --binoculars_only  --prompt --estimated_prompt black-box --ai_source_est phi2 # enhanced black-box detection using estimated prompt generated by phi-2