python detection.py # black-box detection
python detection.py --prompt # white-box detection
# python detection.py --prompt --estimated_prompt --ai_source_est llama # enhanced black-box detection using estimated prompt generated by llama
# python detection.py --prompt --estimated_prompt --ai_source_est neural-chat # enhanced black-box detection using estimated prompt generated by neural-chat
# python detection.py --prompt --estimated_prompt --ai_source_est phi-2 # enhanced black-box detection using estimated prompt generated by phi-2